title: Katiku Munyao
email: katikumunyao@gmail.com
description: >-
  Cybersecurity Engineer passionate about building secure systems and sharing lab-based technical insights.
twitter_username: katikumunyao
github_username: katikumunyao

search: false

# Build settings
markdown: kramdown
# Theme setup
remote_theme: "mmistakes/minimal-mistakes"

# Choose your color skin
minimal_mistakes_skin: "neon"

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Africa/Nairobi  # Set your actual timezone


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache

author:
  name   : "Katiku Munyao"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Cybersecurity engineer with a passion for Blue Team operations and hands-on labs."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/katikumunyao"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/katikumunyao"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:katikumunyao@gmail.com"
header:
  nav:
    - title: "Home"
      url: "/"
    - title: "Resume"
      url: "/resume/"
    - title: "Projects"
      url: "/projects/"
    - title: "Lab Challenges"
      url: "/lab-challenges/"
    - title: "Contact"
      url: "/contact/"

atom_feed:
  hide: true

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/katikumunyao"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:katikumunyao@gmail.com"


defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
